import fs from "fs";

const convert = cookieObj => {
    const header =
        "# Netscape HTTP Cookie File\n" +
        "# This file is generated by a script\n" +
        "# Format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue\n";

    const currentTime = Math.floor(Date.now() / 1000);
    const defaultExpiry = currentTime + 3600 * 24 * 365; // 1 year from now

    const lines = Object.entries(cookieObj).map(([name, cookie]) => {
        const domain = cookie.domain || ".youtube.com";
        const flag = domain.startsWith(".") ? "TRUE" : "FALSE";
        const path = cookie.path || "/";
        const secure = cookie.secure ? "TRUE" : "FALSE";
        const expiry = defaultExpiry;
        const value = cookie.value;

        return `${domain}\t${flag}\t${path}\t${secure}\t${expiry}\t${name}\t${value}`;
    });

    return header + lines.join("\n") + "\n";
};
const handleSetCookie = async (req, res) => {
    try {
        let { cookie } = req.body;

        console.log("setting new cookie ..");

        const newCookie = convert(cookie);
        fs.writeFileSync("cookies.txt", newCookie);

        console.log("Cookie Added");
        res.json({ newCookie, success: true });
    } catch (error) {
        console.error(error);
        res.json({ error, success: false });
    }
};

export default handleSetCookie;
