import fs from "fs";

function fixCookieFile(inputPath, outputPath) {
    const raw = fs.readFileSync(inputPath, "utf-8");

    // Split by ".youtube.com" occurrences
    const parts = raw.split(".youtube.com").filter(Boolean);

    const header = `# Netscape HTTP Cookie File
# This file is generated by a script

`;

    const lines = parts.map(p => {
        const cleaned = p.trim().replace(/\s+/g, "\t");
        return ".youtube.com\t" + cleaned;
    });

    fs.writeFileSync(outputPath, header + lines.join("\n"));
}

fixCookieFile("cookie.txt", "cookies.txt");